### ISSUE TITLE
Skinning Support

### ISSUE THREAD

**Issue by sahin** [mobileplayer/mobileplayer-ios#1]
http://support.jwplayer.com/customer/portal/articles/1413071-skin-xml-reference

Skin Examples:

Netflix
![Neftlix](http://cdn.pttrns.com/228/1799_f.jpg)

Hulu
![hulu](http://cdn.pttrns.com/227/1793_f.jpg)

Facebook
![facebook_h](https://cloud.githubusercontent.com/assets/2508980/7357425/70f2dd58-ece3-11e4-8c3f-a99972cfed99.PNG)

![facebook_v](https://cloud.githubusercontent.com/assets/2508980/7357423/70f15f5a-ece3-11e4-867e-ffcb6c13cb91.PNG)

Vimeo
![vimeo_h](https://cloud.githubusercontent.com/assets/2508980/7357426/70f33438-ece3-11e4-93ee-51e2ade1c878.PNG)
![vimeo_v](https://cloud.githubusercontent.com/assets/2508980/7357424/70f2b7ce-ece3-11e4-821f-63780ea5912b.PNG)

Youtube
![yotube](https://cloud.githubusercontent.com/assets/2508980/7357422/70f15fd2-ece3-11e4-830a-14cc4ee2ea55.PNG)
Super minimalist:

**Comment by nico75005** [comment]
It might be a stupid question but where do we find those JSON skins?
