### ISSUE TITLE
YouTube Example

### ISSUE THREAD

**Issue by dhint4** [mobileplayer/mobileplayer-ios#116]
I have looked all over and have not been able to find a working YouTube example. I know it must exist since #24 added this feature. If anybody could lend me some assistance on which direction to head, that would be greatly appreciated!

**Comment by isair** [comment]
Sorry to inform that it was taken out of the project before the 1.0.0 release. We believe it is better if people use other libraries for parsing video file URLs from pages of video hosting sites, as trying to support that increases the scope of this project significantly and adds a lot of maintenance burden.

**Comment by sahin** [comment]
@isair we already have one. https://github.com/movielala/YoutubeSourceParserKit

**Comment by r-a-o** [comment]
Hi, I am confused, does this player play youtube videos? @isair @sahin Kindly let me know.
