### ISSUE TITLE
Storyboard support

### ISSUE THREAD

**Issue by tuyencoder** [mobileplayer/mobileplayer-ios#119]
Would you please add support for Storyboard as some of us want to use Segue for transition.

Thanks.

**Comment by sahin** [comment]
@tuyencoder good feedback. We have a crazy roadmap to support many cool features, but increasing productivity is always important. we will discuss this internally. 

@tuyencoder do u the mobile player now?

we mostly develop our apps with storyboards to simply PRs and many other things. @isair what do think about support Storyboard?

**Comment by tuyencoder** [comment]
@sahin Yes, I do. The app makes heavy use of Storyboard and [IBAnimatable](https://github.com/JakeLin/IBAnimatable). With two features: Storyboard Reference and Container View, make it easy for me to compose UI.

**Comment by isair** [comment]
This will probably happen after we switch from using MediaPlayer framework to using AVFoundation, as storyboards have an *AVKit Player View Controller* item you can drag and drop.

**Comment by sahin** [comment]
@tuyencoder , I like this issue a lot. It will make things way easier when we have the story board support.

I will add this issue to trello and closing from there... we will just keep the bugs here.
