### ISSUE TITLE
Hiding the share button

### ISSUE THREAD

**Issue by jacks205** [mobileplayer/mobileplayer-ios#120]
Is there a way to hide the share button in the top right of the default video player? It's shows whether or not `activityItems` is set.

Both of these show the button regardless.
```swift
player.activityItems = nil
```
or
```swift
player.activityItems = []
```

Do I need to define a configuration file in order to remove it?

**Comment by isair** [comment]
As you said you can define a configuration with just top bar customization in it where it has a close button and a title label, but not an action button. If you don't want to do that, you can also hide the button view manually using `playerVC. getViewForElementWithIdentifier("action")?.hidden = true`.

However, you have made a good point; it makes sense to hide it when `activityItems` are nil. It's added to the roadmap now.
