### ISSUE TITLE
Load Video (youtube Source) specified time | Save the "exit" time

### ISSUE THREAD

**Issue by fboulegue** [mobileplayer/mobileplayer-ios#127]
Is there a way to load a video with a specified time so it does not start at 0:00?
Is there a way to save the "last played" time via the `close:` function?
If not these would be great improvements :-)!

**Comment by sahin** [comment]
@isair ?

**Comment by isair** [comment]
We don't have APIs specifically designed to do those, but everything you have mentioned is perfectly doable. `MPMoviePlayerController` has an `initialPlaybackTime` property which you can use. As for saving the last played time, just hold the value in a variable and pass it when playing again.

**Comment by fboulegue** [comment]
thanks for the update :-)! :+1:
