### ISSUE TITLE
Slider Circle for short videos goes past the Slider Bar

### ISSUE THREAD

**Issue by jacks205** [mobileplayer/mobileplayer-ios#130]
It seems like that videos up to 7-8 seconds have this issue. This doesn't seem to occur on long videos.

<img width="428" alt="screen shot 2016-03-21 at 1 44 07 pm" src="https://cloud.githubusercontent.com/assets/4063453/13933637/6f05b426-ef6b-11e5-879d-b5077c1e2791.png">

**Comment by sahin** [comment]
@isair can u  confirm?

**Comment by jacks205** [comment]
Any update on this?

**Comment by sahin** [comment]
We easily reproduce it, @isair was working on it. We will have the fix in the next release. it is in our top list. @isair is on holiday now, we will look into it in 7-10 days.

**Comment by isair** [comment]
I'll have time to take a detailed look at this tomorrow, so expect a fix soon.
