### ISSUE TITLE
Fully customized configuration - page not found

### ISSUE THREAD

**Issue by Elyseyvova** [mobileplayer/mobileplayer-ios#131]
A fully customized player configuration file can look like this. - 404 Page not found (

**Comment by sahin** [comment]
@Elyseyvova can u share the url?

**Comment by isair** [comment]
I can't seem to find the sentence you mention in our README. Is it somewhere else?

**Comment by Elyseyvova** [comment]
in this page https://htmlpreview.github.io/?https://github.com/movielala/mobileplayer-ios/blob/master/Documentation/index.html . 

This page not found https://github.com/mobileplayer/mobileplayer-ios/blob/master/MobilePlayerExample/Skin/Netflix.json
