### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by leo150** [mobileplayer/mobileplayer-ios#135]
How can I integrate this player with my project for commercial use?
Your media player is great but Creative Commons license prevents to use it.

**Comment by sahin** [comment]
@leo150 of course. 

http://mobileplayer.io/pricing/
it is free, use it as you want. 

I am bad in licensing :), which licensing you think we should you.

**Comment by leo150** [comment]
Hi, thanks for response 

http://mobileplayer.io/pricing/ conflicts with https://github.com/mobileplayer/mobileplayer-ios#license because I can't use products covered by Creative Commons in _commercial_ app. 

May you cover free part of mobileplayer with [MIT license](https://opensource.org/licenses/MIT) like almost all open-source projects and use some commercial license for analytics and monetization?
