### ISSUE TITLE
Is it possible to add custom headers to request that fetch data?

### ISSUE THREAD

**Issue by Samback** [mobileplayer/mobileplayer-ios#140]
Hi to all,

I am working on project where we need to add additional headers on each one of requests if we authorised. Is it possible to do it on current version?

**Comment by sahin** [comment]
@Samback do u mean? 
while u are requesting the video, u need to headers? right?

**Comment by isair** [comment]
@Samback If you want to add authorization headers to network requests sent by the player, [this](https://stackoverflow.com/questions/16027628/how-to-insert-header-info-into-mpmovieplayercontroller-url) solution should be applicable as we're using MPMoviePlayerController.

**Comment by sahin** [comment]
I am closing this issue @Samback , you can open it back if u need.
