### ISSUE TITLE
Objective-C Support

### ISSUE THREAD

**Issue by Codeido** [mobileplayer/mobileplayer-ios#141]
I believe that support for objective-c can be a good feature.

Thanks

**Comment by kiwi07** [comment]
I need it too, Please....

**Comment by sahin** [comment]
We moved to swift and we are seeing a huge trend in SV, that devs are moving even to react. and in this WWDC they will even launch 3.0 . I think focusing in swift will be better in the future.

**Comment by nipun0505** [comment]
Is there any possibility where I can use this in my objective C code? Not all the features, but only some aspects of it?
