### ISSUE TITLE
Allow rotation only in movie player

### ISSUE THREAD

**Issue by bitomule** [mobileplayer/mobileplayer-ios#142]
I've a portrait only app but I want to allow rotation inside movie player. Is it possible?

I've tried using this small hack:

```
let value = UIInterfaceOrientation.Portrait.rawValue
UIDevice.currentDevice().setValue(value, forKey: "orientation")
```

in viewWillAppear on the presenter view. It works but I see the rotation animation once movie player is dismissed.

Is there any way to allow rotation only inside movie player and once close is pressed rotation is always portrait without any animations?

**Comment by uknowmeright** [comment]
try adding this function to your appDelegate:

` func application(application: UIApplication, supportedInterfaceOrientationsForWindow window: UIWindow?) -> UIInterfaceOrientationMask {

        if let navigationController = self.window?.rootViewController as? UINavigationController {

            if navigationController.visibleViewController is MobilePlayerViewController {
                return UIInterfaceOrientationMask.Landscape
            }
                
            else {
                return UIInterfaceOrientationMask.Portrait
            }
        }

        return UIInterfaceOrientationMask.Portrait
    }
`

**Comment by jhihguan** [comment]
this is good! it's the best answer AFAIK, nice!

**Comment by aloveric** [comment]
Xcode 10 not working when close video, also "Landscape"
