### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by Tulleb** [mobileplayer/mobileplayer-ios#144]
Hello, thanks for your amazing work.

Do you know when it will be Swift 3 ready?

If you create a "swift3" branch, maybe I can take some time to submit a PR.

**Comment by Codeido** [comment]
Thumb up!

**Comment by bitomule** [comment]
Any update on this?

**Comment by bitomule** [comment]
Is this project dead?

**Comment by shamimshamim** [comment]
no

**Comment by isair** [comment]
Sorry for the radio silence, everyone. I'll review the pull requests and update the project until Tuesday, just been a bit swamped lately.
