### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by rezasham** [mobileplayer/mobileplayer-ios#154]
Not sure this is an issue with Carthage, but when building this with Carthage I get an error. Trying to build it with Xcode 8 swift 3.0

**\* Fetching mobileplayer-ios
**\* Checking out mobileplayer-ios 
**\* xcodebuild output can be found in /var/folders/y5/xhb7djqj5kdgymjjvt30g_mw0000gn/T/carthage-xcodebuild.kDlCJr.log
**\* Building scheme "MobilePlayerExampleStores" in MobilePlayer.xcodeproj
*\* CLEAN FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/max/Documents/xcode-projects/Sylabus1x/Carthage/Checkouts/mobileplayer-ios/MobilePlayer.xcodeproj -scheme MobilePlayerExampleStores -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* CLEAN FAILED **

**Comment by isair** [comment]
Could you try again with the latest master?

**Comment by rezasham** [comment]
It works.. thanks. I did however got a few warnings simlar to this one:

ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.0.sdk/Developer/Library/Frameworks'

**Comment by isair** [comment]
Could you provide me with the steps to receive this warning? I can confirm that that path doesn’t exist in the MobilePlayer target’s search paths.

**Comment by rezasham** [comment]
I didnt do anything different than just using Carthage for install/build as previously described. This is warning messages as part of the build process Carthage initiate. 
R





On Fri, Oct 14, 2016 at 9:54 PM +0200, "Baris Sencan" <notifications@github.com> wrote:










Could you provide me with the steps to receive this warning? I can confirm that that path doesn’t exist in the MobilePlayer target’s search paths.
