### ISSUE TITLE
I am getting warning in my project

### ISSUE THREAD

**Issue by stormse** [mobileplayer/mobileplayer-ios#158]
I am getting following warning in my project, it would be great if you can fix this or tell me the way to fix on my side.

(( /Build/Products/Debug-iphonesimulator/MobilePlayer/MobilePlayer.framework/Headers/MobilePlayer-Swift.h:153:41: 'MPMoviePlayerViewController' is deprecated: first deprecated in iOS 9.0 - Use AVPlayerViewController in AVKit. ))

**Comment by zheck** [comment]
If you really want to remove the warning, Just set the target of your project to 8.X

For a cleaner solution:
You need to use AVPlayer and AVPlayerItem inside MobilePlayerViewController
But you cannot just replace 'MPMoviePlayerViewController' by 'AVPlayerViewController' (its method cannot be overridden)

I implemented AVPlayer inside 'MobilePlayerViewController' in my local project, but will need some time to refact my code before proposing a pull request

**Comment by isair** [comment]
Replacing the MPMoviePlayerViewController with AVPlayerLayer is on our
roadmap, but we are busy working on our other products at the moment.
Though any pull requests are most definitely welcome!
