### ISSUE TITLE
Play local mp4 file?

### ISSUE THREAD

**Issue by appcelerate** [mobileplayer/mobileplayer-ios#159]
Its possible to play local mp4 files with this format ->

file:///var/mobile/Containers/Data/Application/962DCBB2-0324-43E6-B6BF-93DBFB6F30F3/Documents/1481639915/highlights/video1.mp4

Thanks :)

**Comment by yukitoto** [comment]
Is it possible?
My app crush when set local url to player view controller.

**Comment by isair** [comment]
For anyone who runs into this issue with a similar question in mind: Whatever is natively supported will work.
