### ISSUE TITLE
How to Remove Share Button

### ISSUE THREAD

**Issue by zeeshanbiit** [mobileplayer/mobileplayer-ios#180]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

# Report

## What did you do?

ℹ Please replace this with what you did.  

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  

## What happened instead?

ℹ Please replace this with of what happened instead.  

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.

**Comment by gkhanacer** [comment]
Is there any one solved it?

**Comment by anonym24** [comment]
yes please add this option

**Comment by anonym24** [comment]
you can comment this line `topBar.addElement(usingConfig: ButtonConfig(dictionary: ["type": "button", "identifier": "action"]))`

in `MobilePlayerControlsView.swift`

**Comment by isair** [comment]
The recommended way of doing this at the moment is by providing your own skin. However, we will add this feature.
