### ISSUE TITLE
Swift 4.2 compatibly 

### ISSUE THREAD

**Issue by MaorS** [mobileplayer/mobileplayer-ios#197]
# Report

## What did you do?

Trying installing mobileplayer using cocoapods on Xcode 10.1 with swift 4.2

## What did you expect to happen?

Install without issues 
 
## What happened instead?

language compatibility issues

## Screenshot

<img width="257" alt="screen shot 2018-12-27 at 20 59 19" src="https://user-images.githubusercontent.com/20594674/50492348-c19bfc00-0a1f-11e9-8fc1-9963bb176c0c.png">

**Comment by mca-shahabuddin** [comment]
Hi @MaorS ,

I have updated code into Swift 4.2.

Please check Fork: https://github.com/mca-shahabuddin/mobileplayer-ios

**Comment by viniciussoares** [comment]
I've submitted a pr for this. #198
