### ISSUE TITLE
1.3.0 podspec version not uploaded to cocoapods

### ISSUE THREAD

**Issue by Streetmage** [mobileplayer/mobileplayer-ios#203]
I wanted to install the latest version of the player, due to podspec file it's 1.3.0, that has Swift 4.2 compatibility. 

But during "pod install" I've noticed that only 1.2.0 is available. After doing "pod update" the version of the player was still 1.2.0. The same is on CocoaPods site https://cocoapods.org/pods/MobilePlayer.

Could you, please, update pod version and upload 1.3.0 to cocoapods?

**Comment by oenama** [comment]
+1

**Comment by isair** [comment]
Apologies for the delay. Pushed a few additional small updates and published 1.3.0.
