### ISSUE TITLE
Xcode11,iOS13. There is a crush!

### ISSUE THREAD

**Issue by l101yakov** [mobileplayer/mobileplayer-ios#208]
<img width="1273" alt="crash" src="https://user-images.githubusercontent.com/55471306/66692806-892a8d80-ecd4-11e9-9119-1e43f1e5354a.png">

**Comment by Droppix** [comment]
similar anomaly

**Comment by nwkeeley** [comment]
@l101yakov or @Droppix  Any luck on this?

**Comment by sam961** [comment]
From Apple docs:
https://developer.apple.com/documentation/mediaplayer/mpmovieplayercontroller

> The MPMoviePlayerController class is formally deprecated in iOS 9. (The MPMoviePlayerViewController class is also formally deprecated.) To play video content in iOS 9 and later, instead use the AVPictureInPictureController or AVPlayerViewController class from the AVKit framework, or the WKWebView class from WebKit.

I think this library will not work any more :(
