### ISSUE TITLE
Use AVPlayerLayer

### ISSUE THREAD

**Issue by isair** [mobileplayer/mobileplayer-ios#77]
Migrate from subclassing MPMoviePlayerViewController to using an AVPlayerLayer as a sublayer.

**Comment by cameronehrlich** [comment]
If you make the video presentation view into a UIView subclass, with a backing AVPlayerLayer, like so:
```objective-c
+ (Class)layerClass
{
    return [AVPlayerLayer class];
}
```
It could pave the way for a lot of cool stuff.  An embedded /inline player style, AutoLayout harmony, and more!

**Comment by FridayDevGroup** [comment]
Agreed, Inline player style would be great.

**Comment by sahin** [comment]
moving this improvement to trello and closing this issue.
